name: Build and deploy Node.js project to Azure Function App - careerwavesinstitute

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'server' # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x' # Set this to the node version to use (supports 8.x, 10.x, 12.x, etc.)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install Dependencies and Build Project'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: 'Zip artifact for deployment'
        run: zip release.zip ./* -r

      - name: 'Upload artifact for deployment job'
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Unzip artifact for deployment'
        run: unzip release.zip
      
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'careerwavesinstitute'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
